openapi: 3.0.0
info:
  title: Whisper API
  description: Whisperモデルを使用して音声ファイルを文字起こしするAPI
  version: 1.0.0
servers:
  - url: http://localhost:5000
    description: ローカルWhisperサーバー
tags:
  - name: stt
    description: 音声からテキストへの変換（Speech to Text）

paths:
  /transcribe:
    post:
      summary: 音声ファイルの文字起こし
      tags:
        - stt
      description: Whisperモデルを使用して音声ファイルを文字起こしします。
      operationId: transcribeAudio
      requestBody:
        required: true
        content:
          audio/wav:
            schema:
              type: string
              format: binary
              description: 文字起こしする音声ファイル（WAV形式など）
      responses:
        '200':
          description: 正常に文字起こしが完了しました
          content:
            application/json:
              schema:
                type: object
                properties:
                  text:
                    type: string
                    description: 音声ファイルから抽出されたテキスト
        '400':
          description: リクエストが無効です（例 音声ファイルが提供されていない場合）
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: エラーの詳細
        '500':
          description: サーバー内部のエラーが発生しました
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: サーバー内のエラーの詳細
