app:
  name: 'go-clean-template'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'
  rollbar_env: 'go-clean-template'

rabbitmq:
  rpc_server_exchange: 'rpc_server'
  rpc_client_exchange: 'rpc_client'

postgres:
  host: localhost
  db: postgres-db
  user: postgres-id
  password: postgres-pw
  port: 5432
  ssl_mode: disable
