/*
 * Whisper API
 *
 * Whisperモデルを使用して音声ファイルを文字起こしするAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

type InlineResponse200 struct {

	// 音声ファイルから抽出されたテキスト
	Text string `json:"text,omitempty"`
}
