/*
 * Whisper API
 *
 * API for transcribing audio files using the Whisper model.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

type InlineResponse200 struct {

	// The transcribed text from the audio file.
	Text string `json:"text,omitempty"`
}
