/*
 * Whisper API
 *
 * API for transcribing audio files using the Whisper model.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

type InlineResponse400 struct {

	// Error message indicating what went wrong.
	Error string `json:"error,omitempty"`
}
