/*
 * Whisper API
 *
 * Whisperモデルを使用して音声ファイルを文字起こしするAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

type InlineResponse500 struct {

	// サーバー内のエラーの詳細
	Error string `json:"error,omitempty"`
}
