openapi: 3.0.0
info:
  description: Whisperモデルを使用して音声ファイルを文字起こしするAPI
  title: Whisper API
  version: 1.0.0
servers:
- description: ローカルWhisperサーバー
  url: http://localhost:5000
tags:
- description: 音声からテキストへの変換（Speech to Text）
  name: stt
paths:
  /transcribe:
    post:
      description: Whisperモデルを使用して音声ファイルを文字起こしします。
      operationId: transcribeAudio
      requestBody:
        content:
          audio/wav:
            schema:
              description: 文字起こしする音声ファイル（WAV形式など）
              format: binary
              type: string
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
          description: 正常に文字起こしが完了しました
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
          description: リクエストが無効です（例 音声ファイルが提供されていない場合）
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_500'
          description: サーバー内部のエラーが発生しました
      summary: 音声ファイルの文字起こし
      tags:
      - stt
components:
  schemas:
    inline_response_200:
      example:
        text: text
      properties:
        text:
          description: 音声ファイルから抽出されたテキスト
          type: string
      type: object
    inline_response_500:
      properties:
        error:
          description: サーバー内のエラーの詳細
          type: string
      type: object
    inline_response_400:
      properties:
        error:
          description: エラーの詳細
          type: string
      type: object
